### ISSUE TITLE
Tests Failing

### ISSUE THREAD

**Issue by jacobseiler** [jacobseiler/sage#4]
I'ved pulled @manodeep 's `lhvt` branch onto my fork and attempted to run the tests (`make tests`).  However these are failing on OzStar.  Full output below

```
./src/tests/test_sage.sh
ThisTask = 0 working on 29585 forests
0%.........10%.........20%.........30%.........40%.........50%.........60%.........70%.........80%.........90%.........100% done. Time taken =  7.692 secs

reading parameter file:

                   FileNameGalaxies      model
                          OutputDir src/auxdata/trees/mini-millennium/
                          FirstFile          0
                           LastFile          7
                         NumOutputs          8
                           TreeName  trees_063
                           TreeType lhalo_binary
                      SimulationDir src/auxdata/trees/mini-millennium/
                   FileWithSnapList src/auxdata/trees/mini-millennium/mini-millennium.a_list
                     LastSnapShotNr         63
                              Omega       0.25
                        OmegaLambda       0.75
                         BaryonFrac       0.17
                           Hubble_h       0.73
                           PartMass  0.0860657
                     SFprescription          0
                        AGNrecipeOn          2
                  SupernovaRecipeOn          1
                     ReionizationOn          1
                  DiskInstabilityOn          1
                      SfrEfficiency       0.05
           FeedbackReheatingEpsilon        3.0
         FeedbackEjectionEfficiency        0.3
              ReIncorporationFactor       0.15
                RadioModeEfficiency       0.08
               QuasarModeEfficiency      0.005
                BlackHoleGrowthRate      0.015
                  ThreshMajorMerger        0.3
             ThresholdSatDisruption        1.0
                              Yield      0.025
                    RecycleFraction       0.43
                     FracZleaveDisk        0.0
                    Reionization_z0        8.0
                    Reionization_zr        7.0
                           EnergySN     1.0e51
                              EtaSN     5.0e-3
                   UnitLength_in_cm 3.08568e+24
                      UnitMass_in_g  1.989e+43
           UnitVelocity_in_cm_per_s     100000

8 snapshots selected for output: 63 37 32 27 23 20 18 16
found 64 defined times in snaplist
cooling functions read


new high mark = 10.6172 MB
Files model_z0.000_0 and output/model_z0.000_0 differ
^M  0%|          | 0/29585 [00:00<?, ?it/s]Printing values that were different side-by side

#######################################
# index          ColdGas1          ColdGas2
2 0.03079371526837349 0.030793720856308937
8 0.10719473659992218 0.10719471424818039
10 0.4891951084136963 0.4891950786113739
13 0.1318044364452362 0.131804421544075
18 0.030337709933519363 0.030337713658809662
19 0.06340668350458145 0.06340667605400085
24 0.40057387948036194 0.4005739390850067
31 0.05011911690235138 0.05011912062764168
38 0.06778661906719208 0.06778662651777267
45 0.20168861746788025 0.20168854296207428
------ Found 10 mis-matched values out of a total of 46 ------
#######################################


Running sagediff on files model_z0.000_0 and output/model_z0.000_0
Traceback (most recent call last):
  File "/home/jseiler/sage/src/tests/sagediff.py", line 316, in <module>
    compare_catalogs(g1, g2)
  File "/home/jseiler/sage/src/tests/sagediff.py", line 287, in compare_catalogs
    raise ValueError(msg)
ValueError: Field = `ColdGas` not the same between the two catalogs

Files model_z1.386_0 and output/model_z1.386_0 differ
^M  0%|          | 0/29585 [00:00<?, ?it/s]Printing values that were different side-by side

#######################################
# index          ColdGas1          ColdGas2
2 0.06440313160419464 0.06440312415361404
18 0.016214733943343163 0.01621473766863346
19 0.2062813639640808 0.20628128945827484
22 0.11758784204721451 0.1175878494977951
24 0.10477963089942932 0.10477960854768753
26 0.005159142427146435 0.0051591224037110806
29 0.20634214580059052 0.20634213089942932
31 0.010598157532513142 0.010598153807222843
38 0.0997815728187561 0.0997815653681755
43 0.329973429441452 0.32997339963912964
45 0.049664177000522614 0.04966416954994202
47 1.293544054031372 1.2935445308685303
52 0.6823491454124451 0.6823490858078003
59 0.0549587644636631 0.0549587607383728
62 0.4025420546531677 0.4025421142578125
63 0.06747764348983765 0.06747763603925705
65 0.5376327037811279 0.5376326441764832
67 0.03371166065335274 0.033711664378643036
74 0.03700629994273186 0.03700629621744156
76 0.02874016761779785 0.028740162029862404
77 0.25596538186073303 0.25596535205841064
78 0.30131295323371887 0.30131298303604126
81 0.062302783131599426 0.06230279058218002
84 0.09790722280740738 0.09790721535682678
86 0.1150791272521019 0.1150791198015213
91 0.454077810049057 0.4540778398513794
104 0.36678293347358704 0.36678290367126465
112 0.1713608354330063 0.17136088013648987
113 0.03802800178527832 0.038027990609407425
116 0.055066827684640884 0.055066850036382675
------ Found 30 mis-matched values out of a total of 120 ------
#######################################


Running sagediff on files model_z1.386_0 and output/model_z1.386_0
Traceback (most recent call last):
  File "/home/jseiler/sage/src/tests/sagediff.py", line 316, in <module>
    compare_catalogs(g1, g2)
  File "/home/jseiler/sage/src/tests/sagediff.py", line 287, in compare_catalogs
    raise ValueError(msg)
ValueError: Field = `ColdGas` not the same between the two catalogs

Files model_z2.070_0 and output/model_z2.070_0 differ
^M  0%|          | 0/29585 [00:00<?, ?it/s]Printing values that were different side-by side

#######################################
# index          ColdGas1          ColdGas2
4 0.10012167692184448 0.10012166947126389
5 0.17956306040287018 0.17956304550170898
14 0.1814412772655487 0.1814412921667099
19 0.10795741528272629 0.1079573929309845
23 0.05267014726996422 0.052670132368803024
24 0.10052889585494995 0.10052890330553055
29 0.10155042260885239 0.10155044496059418
34 0.0936553031206131 0.0936552882194519
35 0.13702218234539032 0.13702213764190674
40 0.27994218468666077 0.2799421548843384
42 0.1257070153951645 0.12570703029632568
45 0.21986795961856842 0.21986794471740723
46 0.21127009391784668 0.21127007901668549
49 0.03307007998228073 0.03307008370757103
58 0.09471292048692703 0.09471301734447479
64 0.3655787706375122 0.3655788004398346
89 0.30177292227745056 0.3017730116844177
91 2.5843617916107178 2.584362268447876
92 0.11560511589050293 0.11560510098934174
112 0.7066176533699036 0.706617534160614
128 0.01904754526913166 0.01904754340648651
------ Found 21 mis-matched values out of a total of 141 ------
#######################################


Running sagediff on files model_z2.070_0 and output/model_z2.070_0
Traceback (most recent call last):
  File "/home/jseiler/sage/src/tests/sagediff.py", line 316, in <module>
    compare_catalogs(g1, g2)
  File "/home/jseiler/sage/src/tests/sagediff.py", line 287, in compare_catalogs
    raise ValueError(msg)
ValueError: Field = `ColdGas` not the same between the two catalogs

Files model_z3.060_0 and output/model_z3.060_0 differ
^M  0%|          | 0/29585 [00:00<?, ?it/s]Printing values that were different side-by side

#######################################
# index          ColdGas1          ColdGas2
0 0.10282189399003983 0.10282188653945923
16 0.17570903897285461 0.17570897936820984
25 0.03968523442745209 0.03968522697687149
33 0.10532503575086594 0.10532506555318832
34 0.015587928704917431 0.015587916597723961
50 0.059916313737630844 0.05991632491350174
56 0.3566439151763916 0.356643944978714
61 0.05238834023475647 0.05238833650946617
69 0.15412479639053345 0.15412475168704987
71 0.21308356523513794 0.21308355033397675
82 0.04202853888273239 0.0420285239815712
86 0.3846573233604431 0.38465726375579834
97 0.01338415127247572 0.013384141959249973
99 0.5366290211677551 0.5366293787956238
103 1.4320476055145264 1.4320472478866577
104 0.12565842270851135 0.12565843760967255
124 0.2268814891576767 0.2268815040588379
126 0.24694764614105225 0.24694761633872986
135 0.07963654398918152 0.07963653653860092
143 0.0715259537100792 0.07152596116065979
------ Found 20 mis-matched values out of a total of 152 ------
#######################################


Running sagediff on files model_z3.060_0 and output/model_z3.060_0
Traceback (most recent call last):
  File "/home/jseiler/sage/src/tests/sagediff.py", line 316, in <module>
    compare_catalogs(g1, g2)
  File "/home/jseiler/sage/src/tests/sagediff.py", line 287, in compare_catalogs
    raise ValueError(msg)
ValueError: Field = `ColdGas` not the same between the two catalogs

Files model_z4.179_0 and output/model_z4.179_0 differ
^M  0%|          | 0/29585 [00:00<?, ?it/s]Printing values that were different side-by side

#######################################
# index          ColdGas1          ColdGas2
10 0.03595941141247749 0.035959407687187195
12 0.09086333215236664 0.09086331725120544
23 0.8930768966674805 0.8930768370628357
24 0.09699739515781403 0.09699740260839462
26 0.010787975043058395 0.010787980630993843
27 0.16554458439350128 0.1655445694923401
28 0.31473806500434875 0.31473803520202637
30 0.1449042409658432 0.144904226064682
42 0.0006608754047192633 0.000660857418552041
44 0.09592878818511963 0.09592879563570023
56 0.0506255067884922 0.0506255105137825
57 0.09087858349084854 0.09087859094142914
70 0.017988745123147964 0.017988743260502815
82 0.033230800181627274 0.03323080763220787
86 0.06195696443319321 0.061956971883773804
97 0.19590531289577484 0.19590529799461365
113 0.07757273316383362 0.07757274061441422
124 0.21031905710697174 0.21031907200813293
128 0.05980440601706505 0.059804413467645645
------ Found 19 mis-matched values out of a total of 133 ------
#######################################


Running sagediff on files model_z4.179_0 and output/model_z4.179_0
Traceback (most recent call last):
  File "/home/jseiler/sage/src/tests/sagediff.py", line 316, in <module>
    compare_catalogs(g1, g2)
  File "/home/jseiler/sage/src/tests/sagediff.py", line 287, in compare_catalogs
    raise ValueError(msg)
ValueError: Field = `ColdGas` not the same between the two catalogs

Files model_z5.289_0 and output/model_z5.289_0 differ
^M  0%|          | 0/29585 [00:00<?, ?it/s]Printing values that were different side-by side

#######################################
# index          ColdGas1          ColdGas2
29 0.15380528569221497 0.15380530059337616
39 0.7193774580955505 0.719377338886261
40 0.19265297055244446 0.19265298545360565
52 0.10731159895658493 0.10731159150600433
56 0.014976243488490582 0.014976240694522858
76 0.08028580993413925 0.08028581738471985
79 0.07267117500305176 0.07267118245363235
81 0.1044536679983139 0.1044536754488945
------ Found 8 mis-matched values out of a total of 103 ------
#######################################


Running sagediff on files model_z5.289_0 and output/model_z5.289_0
Traceback (most recent call last):
  File "/home/jseiler/sage/src/tests/sagediff.py", line 316, in <module>
    compare_catalogs(g1, g2)
  File "/home/jseiler/sage/src/tests/sagediff.py", line 287, in compare_catalogs
    raise ValueError(msg)
ValueError: Field = `ColdGas` not the same between the two catalogs

Files model_z6.197_0 and output/model_z6.197_0 differ
^M  0%|          | 0/29585 [00:00<?, ?it/s]Printing values that were different side-by side

#######################################
# index          ColdGas1          ColdGas2
0 0.10509827733039856 0.10509825497865677
17 0.5338785648345947 0.53387850522995
41 0.07294141501188278 0.07294142246246338
46 0.10395526885986328 0.10395527631044388
49 0.1340751349925995 0.1340751200914383
------ Found 5 mis-matched values out of a total of 66 ------
#######################################


Running sagediff on files model_z6.197_0 and output/model_z6.197_0
Traceback (most recent call last):
  File "/home/jseiler/sage/src/tests/sagediff.py", line 316, in <module>
    compare_catalogs(g1, g2)
  File "/home/jseiler/sage/src/tests/sagediff.py", line 287, in compare_catalogs
    raise ValueError(msg)
ValueError: Field = `ColdGas` not the same between the two catalogs

Files model_z7.272_0 and output/model_z7.272_0 differ
^M  0%|          | 0/29585 [00:00<?, ?it/s]Printing values that were different side-by side

#######################################
# index          ColdGas1          ColdGas2
4 0.4234035015106201 0.4234035313129425
15 0.3376022279262543 0.33760225772857666
------ Found 2 mis-matched values out of a total of 32 ------
#######################################


Running sagediff on files model_z7.272_0 and output/model_z7.272_0
Traceback (most recent call last):
  File "/home/jseiler/sage/src/tests/sagediff.py", line 316, in <module>
    compare_catalogs(g1, g2)
  File "/home/jseiler/sage/src/tests/sagediff.py", line 287, in compare_catalogs
    raise ValueError(msg)
ValueError: Field = `ColdGas` not the same between the two catalogs

Passed: 0. Bitwise identical: 0
Failed: 8
make: *** [tests] Error 8
~                                               
```

The differences are very very minor...

**Comment by manodeep** [comment]
Yup - the tests were failing on ozstar. And the tests were passing on my laptop (I think). This is partially the block I have towards going back and restarting development :'(

**Comment by jacobseiler** [comment]
The biggest difference I saw is on the order of ~5e-7.  Is this enough for us to be worrying over...?

EDIT: Some properties have slightly higher differences (~1e-5) but similar relative differences.

**Comment by manodeep** [comment]
That's the issue - if I can show that those differences are numerical (fused-multiply-adds or something like that), then we can safely ignore these differences. But without that, simply numerically increasing the tolerance might hide future bugs.

**Comment by manodeep** [comment]
Easiest way would be to backtrack through the commits and see where the bug crept in.

**Comment by jacobseiler** [comment]
So I walked back to commit `b814571bde544f172c2ec4576a53444cde615b7b` which had the commit messages

```
    Made the tests a little more stringent. The two z=6 files still produce two incorrect values (passing currently)
```

However the tests still fail on this commit.  I think this may hint that the "correct" data files may have gotten changed at some point.

**Comment by manodeep** [comment]
Do the tests pass on your laptop?

**Comment by manodeep** [comment]
There's also non-zero chance that I moved everything into [lfs_sage](https://github.com/manodeep/lfs_sage)

**Comment by jacobseiler** [comment]
None of the files are bitwise identical however they all pass the `sagediff` test. 

Also, we may wish to move away from lfs somehow (as I explained [here](https://github.com/swincas/cookies-n-code/issues/28))

**Comment by manodeep** [comment]
Yup - lfs was definitely not the way forward

**Comment by jacobseiler** [comment]
Maybe we host it similar to how we have the Mini-Mill trees? You can use your OzStar connections to get that done ;)
